### ISSUE TITLE
problem in .htaccess

### ISSUE THREAD

**Issue by szegi** [zhiephie/boilerplate-slim3#1]
space in .htaccess file
causes problem in my xampp
RewriteRule ^ index.php [QSA, L]
space before L causes
**RewriteRule: bad flag delimiters**

**Comment by zhiephie** [comment]
Hai @szegi, I'm not using xampp, I'm using this php server eg: `php -S localhost:8000 -t public`

**Comment by zhiephie** [comment]
and update like this [e6f8f8c](https://github.com/zhiephie/boilerplate-slim3/commit/781182ea0afb0bec534ce650cac62f794abc33c8)
